# Generated by Django 5.1 on 2024-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='A BlogSpot', max_length=250),
        ),
    ]
