# Generated by Django 5.1 on 2024-09-04 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=250),
        ),
    ]
