# Generated by Django 5.1 on 2024-09-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subtitle',
        ),
    ]
